### ISSUE TITLE
the systemd service never starts

### ISSUE THREAD

**Issue by mgolisch** [TrilliumIT/docker-zfs-plugin#6]
it fails with:
Condition: start condition failed at Sat 2018-02-10 21:57:58 CET; 8min ago
           └─ ConditionPathIsMountPoint=/var/lib/docker-volumes/zfs was not met
What is this start condition good for?
/var/lib/docker-volumes/zfs doesnt seem to be a path used by docker nor do the instructions tell to mount something there.
Removing that and adapting the dataset name to reflect my pools name, makes it start and the volume plugin seems to work correctly.

**Comment by mgolisch** [comment]
am i supposed to set the mountpoint of pool/docker-volumes base dataset to that path?
i noticed that the plugin managed to create and remove volumes but mounting them actualy fails as the mountpoint zfs property is not set on that dataset.
setting it to some path seems to fix that now i can mount the created volumes in a container.

**Comment by travishegner** [comment]
Hi @mgolisch,

Thanks for the report. You'll have to forgive us, as we are good at coding, bad at documentation. :)

When we first wrote the plugin, it was intended to operate with only one pool, for which the above mentioned path (which is the conventional location for most docker storage plugins) was the parent, and all mounted container volumes were children. That is the point in time when the example systemd unit file was documented.

Since then, the driver has been re-factored to allow for any arbitrary pools to be used as the parent dataset, and the systemd example unit file was never updated. The condition is recommended to ensure that ZFS has correctly mounted the intended pools before the plugin starts as a safety measure.

As you've discovered, the new recommended condition should look something like:

```
ConditionPathIsMountPoint=/var/lib/docker-volumes/zfs/pool1
ConditionPathIsMountPoint=/var/lib/docker-volumes/zfs/pool2
```
Also, as you mentioned, the mountpoint on the parent dataset should match the condition paths as well. 

I'll ping @clinta (our local ZFS guru) to ensure that my recommendations are correct.
