### ISSUE TITLE
Full name needed

### ISSUE THREAD

**Issue by lasizoillo** [TrilliumIT/docker-zfs-plugin#8]
lasi@pepino:~$ docker volume create --driver zfs lalalilo
Error response from daemon: create lalalilo: VolumeDriver.Create: exit status 1

lasi@pepino:~$ docker volume create --driver zfs tank/docker-volumes/lalalilo
tank/docker-volumes/lalalilo

I think tank/docker-volumes/ prefix must be transparent to volume creation

**Comment by clinta** [comment]
This is the intended behavior for releases after v0.4.

We needed to support volumes on different pools, and wanted to add the ability to create a volume in any dataset, to do that it is now required to specify the full zfs path to the volume.

**Comment by girstenbrei** [comment]
First of all: Thanks at you all for building this plugin! It works like a charm, I don't quite understand why the zfs driver of docker doesn't provide this functionality by default. And thanks to @lasizoillo for asking this question.

I understand the support for creating volumes in multiple datasets, I think it is a valuable feature. And I also understand the removal of the legacy naming options, as they would not have worked with multiple datasets as they were. But, I also think that the possibility to omit the volume name (e.g. in the compose file) would make it much more readable.

This could be done by either trying to create the volume and if that fails, prepending the default dataset name and try again, or checking if the volume to be created starts with the name of an existing zpool, if yes: create it, if no: prepend the default. This could be enabled via a command line flag (as before 0.5) to avoid breaking compatibility.

I'm sure you had your reasons removing the legacy naming functionality, but would you be interested in a PR keeping support for arbitrary datasets with support for not fully qualified names? Or is there something I am missing, why this would not work?

Thanks for your work,
Chris

**Comment by clinta** [comment]
It's been a while since I've used compose, but it looks like there is now a workaround for their issue of not accepting `/` in a volume name in https://github.com/docker/compose/issues/2837.

It was removed because exposing a volume under multiple names is confusing. A `docker volume ls` will show each volume both in it's fully qualified form, and under it's short name. This can lead to dangerous issues if an admin who is not familiar with this deletes the short named volume then is surprised to discover that this action deleted the fully qualified volume too and their data is gone.
